### ISSUE TITLE
Instructions to compile from source in a Ubuntu machine

### ISSUE THREAD

**Issue by ggerogiokas** [graknlabs/biograkn#40]
Hi,

I was just wondering if you have any instructions to compile biograkn from source 
on a ubuntu machine?

Thanks,
George

**Comment by Irtazaraza** [comment]
Hi George, 
I am working on the automated release pipeline for BioGrakn for all platforms: Windows, Mac and Ubuntu.
Once that is compete you wont need to compile it yourself - Since doing it yourself will entail getting Grakn for Ubuntu and running the entire migration script to migrate the data into Grakn.

**Comment by Irtazaraza** [comment]
will be closed under: issue #41

**Comment by ggerogiokas** [comment]
OK cool! I will just wait for the release then.  I just thought there might be some way I could just compile it myself earlier.
